---
- name: "{{ role_class }} : {{ deploy.subclass }} : assertions"
  assert:
    that:
      - role_class      is defined
      - lifecycle       in [ "install", "uninstall", "start", "stop", "restart" ]
      - deploy.subclass in [ "git" ] # [ "svn", "archive" ]
      - deploy.url      is defined   and   deploy.url       != false
