---
- git:
    repo:    "{{ deploy.url }}"
    clone:   no
    update:  no
    version: "{{ deploy.version | default('HEAD') }}"
  register: register_git_repo

- set_fact:
    deploy_subdirectory: "{{ register_git_repo.after }}"
