---
- include_tasks: "{{ task_file }}"
  loop_control:
    loop_var: task_file
  with_first_found:
    - "{{ role_class }}/{{ ansible_pkg_mgr }}/{{ file }}"
    - "{{ ansible_pkg_mgr }}/{{ file }}"
    - "{{ file }}"
