---
- block:
  - name:   yum update
    become: true
    yum:
      update_cache: true
  when: ansible_pkg_mgr == 'yum'

- block:
  - name:   apt update
    become: true
    apt:
      update_cache: true
  when: ansible_pkg_mgr == 'apt'
