---
- block:
  - command: "service {{ package_service_name }} stop"
    become:  true
  when: package_service_name is defined

- block:
  - import_tasks: 6_stop.yml
  - import_tasks: 6_start.yml
  when: package_service_name is not defined