---
- block:
  - name: "{{ role_class }} : {{ lifecycle }} : stop service"
    service:
      name:  "{{ package_service_name }}"
      state: restarted
    become:  true
  when: package_service_name is defined

- block:
  - include_tasks: 0_file.yml file=6_stop.yml
  - include_tasks: 0_file.yml file=6_start.yml
  when: package_service_name is not defined
