---
- debug:
    msg: "role : package : {{ role_class }} : {{ lifecycle }}"

- include_tasks: 0_file.yml file=0_vars.yml
- include_tasks: 0_file.yml file=0_assertions.yml

- include_tasks: 0_file.yml file=1_repo.yml
- include_tasks: 0_file.yml file=1_update.yml
- include_tasks: 0_file.yml file=2_pre_tasks.yml

- include_tasks: 0_file.yml file=6_stop.yml
  when: lifecycle in [ "uninstall", "stop" ]

- include_tasks: 0_file.yml file=3_package.yml
- include_tasks: 0_file.yml file=4_autoremove.yml
- include_tasks: 0_file.yml file=5_templates.yml

- include_tasks: 0_file.yml file=6_start.yml
  when: lifecycle in [ "install", "start" ]

- include_tasks: 0_file.yml file=6_restart.yml
  when: lifecycle in [ "restart" ]

- include_tasks: 0_file.yml file=9_post_tasks.yml
